python3.12 main.py data/optimize2/config/Apache_AllMeasurements_Performance-.csv | tee results/Apache_AllMeasurements_Performance-.csv
python3.12 main.py data/optimize2/config/SS-B_A-.csv | tee results/SS-B_A-.csv
python3.12 main.py data/optimize2/config/SS-B_B-.csv | tee results/SS-B_B-.csv
python3.12 main.py data/optimize2/config/SS-D_Latency-.csv | tee results/SS-D_Latency-.csv
python3.12 main.py data/optimize2/config/SS-D_Throughput+.csv | tee results/SS-D_Throughput+.csv
python3.12 main.py data/optimize2/config/SS-E_Latency-.csv | tee results/SS-E_Latency-.csv
python3.12 main.py data/optimize2/config/SS-E_Throughput+.csv | tee results/SS-E_Throughput+.csv
python3.12 main.py data/optimize2/config/SS-F_Latency-.csv | tee results/SS-F_Latency-.csv
python3.12 main.py data/optimize2/config/SS-F_Throughput+.csv | tee results/SS-F_Throughput+.csv
python3.12 main.py data/optimize2/config/SS-G_Latency-.csv | tee results/SS-G_Latency-.csv
python3.12 main.py data/optimize2/config/SS-G_Throughput+.csv | tee results/SS-G_Throughput+.csv
python3.12 main.py data/optimize2/config/SS-H_Energy-.csv | tee results/SS-H_Energy-.csv
python3.12 main.py data/optimize2/config/SS-H_Inv_runtime-.csv | tee results/SS-H_Inv_runtime-.csv
python3.12 main.py data/optimize2/config/SS-M_Benchmark-cpu-.csv | tee results/SS-M_Benchmark-cpu-.csv
python3.12 main.py data/optimize2/config/SS-M_Benchmark-energy-.csv | tee results/SS-M_Benchmark-energy-.csv
python3.12 main.py data/optimize2/config/SS-M_Benchmark-time-.csv | tee results/SS-M_Benchmark-time-.csv
python3.12 main.py data/optimize2/config/SS-O_Cpu-.csv | tee results/SS-O_Cpu-.csv
python3.12 main.py data/optimize2/config/SS-O_Performance-.csv | tee results/SS-O_Performance-.csv
python3.12 main.py data/optimize2/config/wc+rs-3d-c4-obj1_Throughput-.csv | tee results/wc+rs-3d-c4-obj1_Throughput-.csv
python3.12 main.py data/optimize2/config/wc+sol-3d-c4-obj1_Throughput-.csv | tee results/wc+sol-3d-c4-obj1_Throughput-.csv
python3.12 main.py data/optimize2/config/wc+wc-3d-c4-obj1_Throughput-.csv | tee results/wc+wc-3d-c4-obj1_Throughput-.csv
python3.12 main.py data/optimize2/config/wc-6d-c1-obj1_Throughput-.csv | tee results/wc-6d-c1-obj1_Throughput-.csv
python3.12 main.py data/optimize2/misc/auto93_Acc+.csv | tee results/auto93_Acc+.csv
python3.12 main.py data/optimize2/misc/auto93_Lbs-.csv | tee results/auto93_Lbs-.csv
python3.12 main.py data/optimize2/misc/auto93_Mpg+.csv | tee results/auto93_Mpg+.csv
python3.12 main.py data/optimize2/process/nasa93dem_Defects-.csv | tee results/nasa93dem_Defects-.csv
python3.12 main.py data/optimize2/process/nasa93dem_Effort-.csv | tee results/nasa93dem_Effort-.csv
python3.12 main.py data/optimize2/process/nasa93dem_Kloc+.csv | tee results/nasa93dem_Kloc+.csv
python3.12 main.py data/optimize2/process/nasa93dem_Months-.csv | tee results/nasa93dem_Months-.csv
python3.12 main.py data/optimize2/process/pom3d_Cost-.csv | tee results/pom3d_Cost-.csv
python3.12 main.py data/optimize2/process/pom3d_Idle-.csv | tee results/pom3d_Idle-.csv
python3.12 main.py data/optimize2/process/pom3d_Score-.csv | tee results/pom3d_Score-.csv

python3.12 main.py data/optimize2/config/HSMGP_num_AverageTimePerIteration-.csv | tee results/HSMGP_num_AverageTimePerIteration-.csv
python3.12 main.py data/optimize2/config/rs-6d-c3_obj1_Throughput-.csv | tee results/rs-6d-c3_obj1_Throughput-.csv
python3.12 main.py data/optimize2/config/rs-6d-c3_obj2_Latency-.csv | tee results/rs-6d-c3_obj2_Latency-.csv
python3.12 main.py data/optimize2/config/sol-6d-c2-obj1_Throughput-.csv | tee results/sol-6d-c2-obj1_Throughput-.csv
python3.12 main.py data/optimize2/config/SS-A_Latency-.csv | tee results/SS-A_Latency-.csv
python3.12 main.py data/optimize2/config/SS-A_Throughput+.csv | tee results/SS-A_Throughput+.csv
python3.12 main.py data/optimize2/config/SS-C_Latency-.csv | tee results/SS-C_Latency-.csv
python3.12 main.py data/optimize2/config/SS-C_Throughput+.csv | tee results/SS-C_Throughput+.csv
python3.12 main.py data/optimize2/config/SS-I_Latency-.csv | tee results/SS-I_Latency-.csv
python3.12 main.py data/optimize2/config/SS-I_Throughput+.csv | tee results/SS-I_Throughput+.csv
python3.12 main.py data/optimize2/config/SS-J_Latency-.csv | tee results/SS-J_Latency-.csv
python3.12 main.py data/optimize2/config/SS-J_Throughput+.csv | tee results/SS-J_Throughput+.csv
python3.12 main.py data/optimize2/config/SS-K_Latency-.csv | tee results/SS-K_Latency-.csv
python3.12 main.py data/optimize2/config/SS-K_Throughput+.csv | tee results/SS-K_Throughput+.csv
python3.12 main.py data/optimize2/config/SS-L_A-.csv | tee results/SS-L_A-.csv
python3.12 main.py data/optimize2/config/SS-L_B-.csv | tee results/SS-L_B-.csv
python3.12 main.py data/optimize2/config/SS-P_A-.csv | tee results/SS-P_A-.csv
python3.12 main.py data/optimize2/config/SS-P_B-.csv | tee results/SS-P_B-.csv
python3.12 main.py data/optimize2/config/SS-Q_Cpu-.csv | tee results/SS-Q_Cpu-.csv
python3.12 main.py data/optimize2/config/SS-Q_Energy-.csv | tee results/SS-Q_Energy-.csv
python3.12 main.py data/optimize2/config/SS-Q_Performance-.csv | tee results/SS-Q_Performance-.csv
python3.12 main.py data/optimize2/config/SS-R_Cpu-.csv | tee results/SS-R_Cpu-.csv
python3.12 main.py data/optimize2/config/SS-R_Performance-.csv | tee results/SS-R_Performance-.csv
python3.12 main.py data/optimize2/config/SS-S_Latency-.csv | tee results/SS-S_Latency-.csv
python3.12 main.py data/optimize2/config/SS-S_Throughput-.csv | tee results/SS-S_Throughput-.csv
python3.12 main.py data/optimize2/config/X264_AllMeasurements_Performance-.csv | tee results/X264_AllMeasurements_Performance-.csv
python3.12 main.py data/optimize2/misc/dataset_Facebook_Comment+.csv | tee results/dataset_Facebook_Comment+.csv
python3.12 main.py data/optimize2/misc/dataset_Facebook_Like+.csv | tee results/dataset_Facebook_Like+.csv
python3.12 main.py data/optimize2/misc/dataset_Facebook_Share+.csv | tee results/dataset_Facebook_Share+.csv
python3.12 main.py data/optimize2/misc/dataset_Facebook_TotalInteractions+.csv | tee results/dataset_Facebook_TotalInteractions+.csv
python3.12 main.py data/optimize2/misc/ENB2012_data_Y1+.csv | tee results/ENB2012_data_Y1+.csv
python3.12 main.py data/optimize2/misc/ENB2012_data_Y2+.csv | tee results/ENB2012_data_Y2+.csv
python3.12 main.py data/optimize2/misc/real_estate_valuation_PricePerUnit+.csv | tee results/real_estate_valuation_PricePerUnit+.csv
python3.12 main.py data/optimize2/misc/SeoulBikeData_Rents+.csv | tee results/SeoulBikeData_Rents+.csv
python3.12 main.py data/optimize2/misc/TetuanCitypowerconsumption_Zone1-.csv | tee results/TetuanCitypowerconsumption_Zone1-.csv
python3.12 main.py data/optimize2/misc/TetuanCitypowerconsumption_Zone2-.csv | tee results/TetuanCitypowerconsumption_Zone2-.csv
python3.12 main.py data/optimize2/misc/TetuanCitypowerconsumption_Zone3-.csv | tee results/TetuanCitypowerconsumption_Zone3-.csv
python3.12 main.py data/optimize2/misc/Wine_quality_Alcohol-.csv | tee results/Wine_quality_Alcohol-.csv
python3.12 main.py data/optimize2/misc/Wine_quality_Quality+.csv | tee results/Wine_quality_Quality+.csv
python3.12 main.py data/optimize2/process/coc1000_AEXP-.csv | tee results/coc1000_AEXP-.csv
python3.12 main.py data/optimize2/process/coc1000_EFFORT-.csv | tee results/coc1000_EFFORT-.csv
python3.12 main.py data/optimize2/process/coc1000_PLEX-.csv | tee results/coc1000_PLEX-.csv
python3.12 main.py data/optimize2/process/coc1000_RISK-.csv | tee results/coc1000_RISK-.csv
python3.12 main.py data/optimize2/process/coc1000_LOC+.csv | tee results/coc1000_LOC+.csv
python3.12 main.py data/optimize2/process/pom3a_Cost-.csv | tee results/pom3a_Cost-.csv
python3.12 main.py data/optimize2/process/pom3a_Idle-.csv | tee results/pom3a_Idle-.csv
python3.12 main.py data/optimize2/process/pom3a_Score-.csv | tee results/pom3a_Score-.csv
python3.12 main.py data/optimize2/process/pom3b_Cost-.csv | tee results/pom3b_Cost-.csv
python3.12 main.py data/optimize2/process/pom3b_Idle-.csv | tee results/pom3b_Idle-.csv
python3.12 main.py data/optimize2/process/pom3b_Score-.csv | tee results/pom3b_Score-.csv
python3.12 main.py data/optimize2/process/pom3c_Cost-.csv | tee results/pom3c_Cost-.csv
python3.12 main.py data/optimize2/process/pom3c_Idle-.csv | tee results/pom3c_Idle-.csv
python3.12 main.py data/optimize2/process/pom3c_Score-.csv | tee results/pom3c_Score-.csv