python3.12 main.py data/optimize/config/Apache_AllMeasurements.csv | tee results/Apache_AllMeasurements.csv
python3.12 main.py data/optimize/config/SS-B.csv | tee results/SS-B.csv
python3.12 main.py data/optimize/config/SS-D.csv | tee results/SS-D.csv
python3.12 main.py data/optimize/config/SS-E.csv | tee results/SS-E.csv
python3.12 main.py data/optimize/config/SS-F.csv | tee results/SS-F.csv
python3.12 main.py data/optimize/config/SS-G.csv | tee results/SS-G.csv
python3.12 main.py data/optimize/config/SS-H.csv | tee results/SS-H.csv
python3.12 main.py data/optimize/config/SS-M.csv | tee results/SS-M.csv
python3.12 main.py data/optimize/config/SS-O.csv | tee results/SS-O.csv
python3.12 main.py data/optimize/config/wc+rs-3d-c4-obj1.csv | tee results/wc+rs-3d-c4-obj1.csv
python3.12 main.py data/optimize/config/wc+sol-3d-c4-obj1.csv | tee results/wc+sol-3d-c4-obj1.csv
python3.12 main.py data/optimize/config/wc+wc-3d-c4-obj1.csv | tee results/wc+wc-3d-c4-obj1.csv
python3.12 main.py data/optimize/misc/auto93.csv | tee results/auto93.csv
python3.12 main.py data/optimize/misc/real_estate_valuation.csv | tee results/real_estate_valuation.csv
python3.12 main.py data/optimize/process/nasa93dem.csv | tee results/nasa93dem.csv
python3.12 main.py data/optimize/process/pom3d.csv | tee results/pom3d.csv