python3.11 main.py data/optimize2/config/Apache_AllMeasurements_Performance-.csv | tee results/Apache_AllMeasurements_Performance-.csv
python3.11 main.py data/optimize2/config/SS-B_A-.csv | tee results/SS-B_A-.csv
python3.11 main.py data/optimize2/config/SS-B_B-.csv | tee results/SS-B_B-.csv
python3.11 main.py data/optimize2/config/SQL_AllMeasurements_Performance-.csv | tee results/SQL_AllMeasurements_Performance-.csv
python3.11 main.py data/optimize2/config/SS-T_Benchmark-cpu-.csv | tee results/SS-T_Benchmark-cpu-.csv
python3.11 main.py data/optimize2/config/SS-T_Performance-.csv | tee results/SS-T_Performance-.csv
python3.11 main.py data/optimize2/config/SS-U_Benchmark-cpu-.csv | tee results/SS-U_Benchmark-cpu-.csv
python3.11 main.py data/optimize2/config/SS-U_Benchmark-iperf-.csv | tee results/SS-U_Benchmark-iperf-.csv
python3.11 main.py data/optimize2/config/SS-V_Cpu-.csv | tee results/SS-V_Cpu-.csv
python3.11 main.py data/optimize2/config/SS-V_Performance-.csv | tee results/SS-V_Performance-.csv
python3.11 main.py data/optimize2/hpo/healthCloseIsses11mths0001-hard_ACC+.csv | tee results/healthCloseIsses11mths0001-hard_ACC+.csv
python3.11 main.py data/optimize2/hpo/healthCloseIsses11mths0001-hard_MRE-.csv | tee results/healthCloseIsses11mths0001-hard_MRE-.csv
python3.11 main.py data/optimize2/hpo/healthCloseIsses11mths0001-hard_PRED40+.csv | tee results/healthCloseIsses11mths0001-hard_PRED40+.csv
python3.11 main.py data/optimize2/hpo/healthCloseIsses11mths0011-easy_ACC+.csv | tee results/healthCloseIsses11mths0011-easy_ACC+.csv
python3.11 main.py data/optimize2/hpo/healthCloseIsses11mths0011-easy_MRE-.csv | tee results/healthCloseIsses11mths0011-easy_MRE-.csv
python3.11 main.py data/optimize2/hpo/healthCloseIsses11mths0011-easy_PRED40+.csv | tee results/healthCloseIsses11mths0011-easy_PRED40+.csv
python3.11 main.py data/optimize2/process/xomo_flight_DEFECTS-.csv | tee results/xomo_flight_DEFECTS-.csv
python3.11 main.py data/optimize2/process/xomo_flight_EFFORT-.csv | tee results/xomo_flight_EFFORT-.csv
python3.11 main.py data/optimize2/process/xomo_flight_MONTHS-.csv | tee results/xomo_flight_MONTHS-.csv
python3.11 main.py data/optimize2/process/xomo_flight_RISKS-.csv | tee results/xomo_flight_RISKS-.csv
python3.11 main.py data/optimize2/process/xomo_ground_DEFECTS-.csv | tee results/xomo_ground_DEFECTS-.csv
python3.11 main.py data/optimize2/process/xomo_ground_EFFORT-.csv | tee results/xomo_ground_EFFORT-.csv
python3.11 main.py data/optimize2/process/xomo_ground_MONTHS-.csv | tee results/xomo_ground_MONTHS-.csv
python3.11 main.py data/optimize2/process/xomo_ground_RISKS-.csv | tee results/xomo_ground_RISKS-.csv
python3.11 main.py data/optimize2/process/xomo_osp2_DEFECTS-.csv | tee results/xomo_osp2_DEFECTS-.csv
python3.11 main.py data/optimize2/process/xomo_osp2_EFFORT-.csv | tee results/xomo_osp2_EFFORT-.csv
python3.11 main.py data/optimize2/process/xomo_osp2_MONTHS-.csv | tee results/xomo_osp2_MONTHS-.csv
python3.11 main.py data/optimize2/process/xomo_osp2_RISKS-.csv | tee results/xomo_osp2_RISKS-.csv
python3.11 main.py data/optimize2/process/xomo_osp_DEFECTS-.csv | tee results/xomo_osp_DEFECTS-.csv
python3.11 main.py data/optimize2/process/xomo_osp_EFFORT-.csv | tee results/xomo_osp_EFFORT-.csv
python3.11 main.py data/optimize2/process/xomo_osp_MONTHS-.csv | tee results/xomo_osp_MONTHS-.csv
python3.11 main.py data/optimize2/process/xomo_osp_RISKS-.csv | tee results/xomo_osp_RISKS-.csv


python3.11 main.py data/optimize2/config/SS-N_Energy-.csv | tee results/SS-N_Energy-.csv
python3.11 main.py data/optimize2/config/SS-N_PSNR-.csv | tee results/SS-N_PSNR-.csv
python3.11 main.py data/optimize2/config/SS-W_Cpu-.csv | tee results/SS-W_Cpu-.csv
python3.11 main.py data/optimize2/config/SS-W_Performance-.csv | tee results/SS-W_Performance-.csv
python3.11 main.py data/optimize2/config/SS-X_Compile-performance-.csv | tee results/SS-X_Compile-performance-.csv
python3.11 main.py data/optimize2/config/SS-X_Fixed-compile-cpu-.csv | tee results/SS-X_Fixed-compile-cpu-.csv